# Generated by Django 4.2.3 on 2023-09-13 18:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import users.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.film')),
            ],
        ),
        migrations.CreateModel(
            name='FollowLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('profile_image', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('backdrop_image', models.ImageField(blank=True, upload_to='user_backdrops')),
                ('bio', models.TextField(blank=True, max_length=512)),
                ('dob', models.DateField(null=True, validators=[users.models.validate_age])),
                ('favourites', models.ManyToManyField(blank=True, through='users.FavLog', to='core.film')),
                ('following', models.ManyToManyField(blank=True, through='users.FollowLog', to='users.profile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('watchlist', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.list')),
            ],
        ),
        migrations.AddField(
            model_name='followlog',
            name='followee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followee', to='users.profile'),
        ),
        migrations.AddField(
            model_name='followlog',
            name='follower',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follower', to='users.profile'),
        ),
        migrations.AddField(
            model_name='favlog',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profile'),
        ),
    ]
