# Generated by Django 4.2.3 on 2023-09-13 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_list_user'),
        ('users', '0002_remove_profile_watchlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='watchlist',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.list'),
        ),
    ]
