# Generated by Django 4.2.3 on 2023-09-16 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_watchlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='backdrop_image',
        ),
        migrations.AddField(
            model_name='profile',
            name='cover_image',
            field=models.ImageField(blank=True, upload_to='user_covers'),
        ),
    ]
