# Generated by Django 4.2.3 on 2023-09-27 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_profile_backdrop_image_profile_cover_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='followlog',
            old_name='time',
            new_name='date',
        ),
    ]
