# Generated by Django 4.2.3 on 2023-09-13 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_filmlistlog_date_added'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list',
            name='user',
        ),
    ]
