# Generated by Django 4.2.3 on 2023-09-16 22:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0005_alter_filmlistlog_options_alter_log_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='LikeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('gapt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.gapt')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='gapt',
            name='likes',
            field=models.ManyToManyField(related_name='likes', through='core.LikeLog', to=settings.AUTH_USER_MODEL),
        ),
    ]
