# Generated by Django 4.2.3 on 2023-09-17 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_log_date_regaptlog_gapt_regapts'),
    ]

    operations = [
        migrations.RenameField('Gapt', 'datePosted', 'date'),
    ]
