# Generated by Django 4.2.3 on 2023-09-18 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_log_date_filmoftheweek'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FilmOfTheWeek',
        ),
    ]
