# Generated by Django 4.2.3 on 2023-09-18 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_delete_filmoftheweek'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilmOfTheWeek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.film')),
            ],
        ),
    ]
