# Generated by Django 4.2.3 on 2023-09-27 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_log_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name_plural': 'People'},
        ),
    ]
