# Generated by Django 4.2.3 on 2023-09-29 18:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_filmoftheweek_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filmoftheweek',
            name='end_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='filmoftheweek',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
