# Generated by Django 4.2.3 on 2023-10-01 18:03

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_filmoftheweek_summary_picture_path_alter_log_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='date',
            field=models.DateField(default=datetime.date.today, validators=[django.core.validators.MaxValueValidator(datetime.date(2023, 10, 1), message='You have entered a date that is beyond the current timeline. Please check your flux capacitor and try again.')]),
        ),
        migrations.DeleteModel(
            name='FilmOfTheWeek',
        ),
    ]
