# Generated by Django 4.2.3 on 2023-09-03 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='messages',
            field=models.ManyToManyField(blank=True, to='chat.message'),
        ),
    ]
