# Generated by Django 4.2.3 on 2023-10-01 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filmOfTheWeek', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filmoftheweek',
            old_name='summary_picture_path',
            new_name='backdrop_path',
        ),
    ]
