# Generated by Django 4.2.3 on 2023-09-26 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likenotification',
            name='reciever',
        ),
    ]
