# Generated by Django 4.2.3 on 2023-09-27 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_log_date'),
        ('notifications', '0002_remove_likenotification_reciever'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likenotification',
            name='gapt',
        ),
        migrations.RemoveField(
            model_name='likenotification',
            name='likers',
        ),
        migrations.AddField(
            model_name='likenotification',
            name='like_log',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.likelog'),
        ),
        migrations.AddField(
            model_name='likenotification',
            name='read',
            field=models.BooleanField(default=False),
        ),
    ]
