# Generated by Django 4.2.3 on 2023-09-27 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('notifications', '0004_alter_likenotification_like_log'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likenotification',
            name='like_log',
        ),
        migrations.AddField(
            model_name='likenotification',
            name='content_type',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='likenotification',
            name='object_id',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='likenotification',
            index=models.Index(fields=['content_type', 'object_id'], name='notificatio_content_5fecc3_idx'),
        ),
    ]
