# Generated by Django 4.2.3 on 2023-09-27 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('notifications', '0005_remove_likenotification_like_log_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LikeNotification',
            new_name='ActivityNotification',
        ),
        migrations.RenameIndex(
            model_name='activitynotification',
            new_name='notificatio_content_63ee72_idx',
            old_name='notificatio_content_5fecc3_idx',
        ),
    ]
