# Generated by Django 4.2.3 on 2023-09-27 15:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0008_activitynotification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitynotification',
            name='date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
