# Generated by Django 4.2.3 on 2023-09-27 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0009_activitynotification_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitynotification',
            name='date',
            field=models.DateTimeField(blank=True),
        ),
    ]
